---

# SPDX-FileCopyrightText: 2024 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

include:
  - project: "univention/dev/nubus-for-k8s/common-ci"
    ref: "v1.68.2"
    file:
      - "defaults/stages.yaml"
      - "defaults/nubus-workflow.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/container-build-external-buildkit.yaml"
      - "jobs/check-debian-updates.yaml"
      - "templates/sonarqube.yaml"

.build-matrix: &build-matrix
  - IMAGE_NAME:
      - "wait-for-dependency"
    BUILD_CONTEXT: "$CI_PROJECT_DIR/docker/wait-for-dependency/"

container-build:
  parallel:
    matrix: *build-matrix

container-malware-scan:
  parallel:
    matrix: *build-matrix

push-image-external:
  parallel:
    matrix: *build-matrix

container-sign-external:
  parallel:
    matrix: *build-matrix

container-release-attestation:
  parallel:
    matrix: *build-matrix

check-debian-updates:
  parallel:
    matrix: *build-matrix
  variables:
    TARGET_IMAGE: "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:latest"

sonarqube:
  extends: .sonarqube
  needs: []

...
